### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Cxetive** [Androz2091/giveaways-bot#12]
So I keep getting the error, (node:6086) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'start' of undefined
    at Object.run (/root/ew/commands/owner/create.js:47:26)
    at module.exports (/root/ew/events/guild/message.js:15:38)
    at Client.emit (events.js:198:13)
    at MessageCreateHandler.handle (/root/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/root/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/root/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/root/node_modules/ws/lib/websocket.js:789:20)
(node:6086) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6086) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

How can I fix this

**Comment by Cxetive** [comment]
Also, this is my command https://paste.menudocs.org/paste/92vw4

**Comment by Cxetive** [comment]
@Androz2091 Please help me

**Comment by Cxetive** [comment]
Fixed it my self!

**Comment by Cxetive** [comment]
Fixed it myself!

**Comment by Androz2091** [comment]
👌
