### ISSUE TITLE
SyntaxError: The storage file is not properly formatted.

### ISSUE THREAD

**Issue by sysysysy242** [Androz2091/giveaways-bot#19]
I have this error : 

(node:16156) UnhandledPromiseRejectionWarning: SyntaxError: The storage file is not properly formatted.
    at GiveawaysManager._initStorage (d:\Bureau\GiveawayBot-master\node_modules\discord-giveaways\src\Manager.js:325:27)
    at async GiveawaysManager._init (d:\Bureau\GiveawayBot-master\node_modules\discord-giveaways\src\Manager.js:416:26)

**Comment by Cxetive** [comment]
If I remember right you need to format it like

[
]

**Comment by sysysysy242** [comment]
where i impute this?

**Comment by sysysysy242** [comment]
how , i get this , thx !!
