### ISSUE TITLE
SyntaxError: The storage file is not properly formatted

### ISSUE THREAD

**Issue by whitskin** [Androz2091/giveaways-bot#24]
**Hello I'm using commando this is the error I got**

```
0|shard    | (node:31837) UnhandledPromiseRejectionWarning: SyntaxError: The storage file is not properly formatted.
0|shard    |     at GiveawaysManager.getAllGiveaways (/root/dreambot/node_modules/discord-giveaways/src/Manager.js:272:27)
0|shard    |     at async GiveawaysManager._init (/root/dreambot/node_modules/discord-giveaways/src/Manager.js:363:26)
0|shard    | (node:31837) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
0|shard    | (node:31837) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Androz2091** [comment]
Hello,
This is going to be fixed.

**Comment by whitskin** [comment]
Is the problem fixed?

**Comment by Androz2091** [comment]
@whitskin can you try to install the package using Github? (`npm install Androz2091/discord-giveaways`) and retry? You should have more informations in the console.

**Comment by whitskin** [comment]
Error

```
7|shard  | SyntaxError: The storage file is not properly formatted.
7|shard |     at GiveawaysManager.getAllGiveaways (/root/dreambot/node_modules/discord-giveaways/src/Manager.js:273:27)
7|shard |     at async GiveawaysManager._init (/root/dreambot/node_modules/discord-giveaways/src/Manager.js:364:26)

```
