### ISSUE TITLE
TypeError: fields.flat is not a function

### ISSUE THREAD

**Issue by GenryMg** [Androz2091/giveaways-bot#28]
I got this error when running the bot:

```
(node:6025) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/rbd/pnpm-volume/665aec89-f0d0-4faf-8158-5652ead2c334/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/structures/MessageEmbed.js:443:8)
    at MessageEmbed.setup (/rbd/pnpm-volume/665aec89-f0d0-4faf-8158-5652ead2c334/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/structures/MessageEmbed.js:77:91)
    at new MessageEmbed (/rbd/pnpm-volume/665aec89-f0d0-4faf-8158-5652ead2c334/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/rbd/pnpm-volume/665aec89-f0d0-4faf-8158-5652ead2c334/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/structures/APIMessage.js:164:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/rbd/pnpm-volume/665aec89-f0d0-4faf-8158-5652ead2c334/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/structures/APIMessage.js:164:31)
    at TextChannel.send (/rbd/pnpm-volume/665aec89-f0d0-4faf-8158-5652ead2c334/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at Promise (/rbd/pnpm-volume/665aec89-f0d0-4faf-8158-5652ead2c334/node_modules/.registry.npmjs.org/discord-giveaways/3.2.3/node_modules/discord-giveaways/src/Manager.js:179:41)
    at new Promise (<anonymous>)
    at GiveawaysManager.start (/rbd/pnpm-volume/665aec89-f0d0-4faf-8158-5652ead2c334/node_modules/.registry.npmjs.org/discord-giveaways/3.2.3/node_modules/discord-giveaways/src/Manager.js:135:16)
(node:6025) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6025) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by Androz2091** [comment]
@GenryMg You must update Node.js to v12 or newer.
