### ISSUE TITLE
ReferenceError: error is not defined

### ISSUE THREAD

**Issue by ACES111** [Androz2091/giveaways-bot#51]
i need help fixing this if you know how 

(node:41652) UnhandledPromiseRejectionWarning: ReferenceError: error is not defined
    at GiveawaysManager.getAllGiveaways (C:\Users\brand\Desktop\NT BOT\bot\node_modules\discord-giveaways\src\Manager.js:289:75)
    at GiveawaysManager._init (C:\Users\brand\Desktop\NT BOT\bot\node_modules\discord-giveaways\src\Manager.js:391:41)
    at new GiveawaysManager (C:\Users\brand\Desktop\NT BOT\bot\node_modules\discord-giveaways\src\Manager.js:57:14)
    at Object.<anonymous> (C:\Users\brand\Desktop\NT BOT\bot\index.js:10:27)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:41652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:41652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Noobforlife** [comment]
I get the exact same error. did u manage to fix it?

**Comment by needhamgary** [comment]
Send in that line of code to better assist you guys

**Comment by Androz2091** [comment]
It's now fixed 👍

**Comment by Noobforlife** [comment]
@Androz2091 i updated and still getting the same

**Comment by ACES111** [comment]
that's a bit rude you close it ever tho the one who make it didn't get it fix
