### ISSUE TITLE
@everyone is mentioned when giveaway starts and ends

### ISSUE THREAD

**Issue by SGAHJDGAJHDGSA** [Androz2091/giveaways-bot#6]
This package is AMAZING, but I have a few suggestions you don't need to do any of this. One suggestion is to make it possible for people to add an option that displays Winner count, because right now it only says "React with 🎉to enter" and the time. I feel there should also be an option to add in "Winner count:" The second suggestion is making the @everyone message when giveaway started optional or custom! Hopefully you have read this and are willing to make some changes (keep in mind this is a simple note not mandatory)
                                                                                                                                            - Thanks Again!

**Comment by Androz2091** [comment]
The winner count is already displayed, no?

<img width="183" alt="Capture d’écran 2020-02-13 à 09 28 56" src="https://user-images.githubusercontent.com/42497995/74415265-525fb200-4e43-11ea-8c6c-96389e34f198.png">

**Comment by Zaid-maker** [comment]
Thank you for making this possible

**Comment by SGAHJDGAJHDGSA** [comment]
Yeah I guess, but is there away to get rid of the @everyone and make it a custom message?

**Comment by Androz2091** [comment]
@SGAHJDGAJHDGSA yes, check the config.json file

**Comment by Androz2091** [comment]
Just set the `everyoneMention` to `false`

**Comment by SGAHJDGAJHDGSA** [comment]
I did that and I get this error...

> (node:790) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'everyoneMention' of undefined

**Comment by Androz2091** [comment]
That's strange... Can you send the full part of the error?

**Comment by SGAHJDGAJHDGSA** [comment]
Full error`(node:790) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'everyoneMention' of undefined
    at Object.run (/Users/PL/Desktop/Tyler Works-DONTrash/The Creek Tools/commands/Giveaways/start.js:38:39)
    at module.exports (/Users/PL/Desktop/Tyler Works-DONTrash/The Creek Tools/events/guild/message.js:12:33)
    at Client.emit (events.js:198:13)
    at MessageCreateHandler.handle (/Users/PL/Desktop/Tyler Works-DONTrash/The Creek Tools/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/Users/PL/Desktop/Tyler Works-DONTrash/The Creek Tools/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/Users/PL/Desktop/Tyler Works-DONTrash/The Creek Tools/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/Users/PL/Desktop/Tyler Works-DONTrash/The Creek Tools/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/Users/PL/Desktop/Tyler Works-DONTrash/The Creek Tools/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/Users/PL/Desktop/Tyler Works-DONTrash/The Creek Tools/node_modules/ws/lib/websocket.js:789:20)
(node:790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:790) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.` should I define config?

**Comment by Androz2091** [comment]
Hmm it should be defined here: https://github.com/Androz2091/giveaways-bot/blob/master/index.js#L7

**Comment by SGAHJDGAJHDGSA** [comment]
Ah

**Comment by Androz2091** [comment]
Can you send me the content of your `config.json` file?

**Comment by SGAHJDGAJHDGSA** [comment]
```{
    "token" : "NjMzMzI3MDQyNTkwNTM5Nzc2.Xfv7XA.I72n3oGJ4nSYP8TNCAzvdxX4xpk",
    "prefix" : "o!",
    "everyoneMention": false
}
``` It works now, but it be possible for me to add an option like hosted by under the timer?

**Comment by Androz2091** [comment]
Yes, open another issue please
