### ISSUE TITLE
It doesnt send giveaway in the channel, but shows giveaway started!

### ISSUE THREAD

**Issue by AK1233** [Androz2091/giveaways-bot#63]
Please help me it shows giveaway started in #channel. but nothing happends

**Comment by AK1233** [comment]
with this error: (node:3263) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function

    at Function.normalizeFields (/rbd/pnpm-volume/fd2eb835-c483-4238-9921-9a54026057fb/node_modules/.registry.npmjs.org/discord.js/12.4.1/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)

    at MessageEmbed.setup (/rbd/pnpm-volume/fd2eb835-c483-4238-9921-9a54026057fb/node_modules/.registry.npmjs.org/discord.js/12.4.1/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)

    at new MessageEmbed (/rbd/pnpm-volume/fd2eb835-c483-4238-9921-9a54026057fb/node_modules/.registry.npmjs.org/discord.js/12.4.1/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)

    at embedLikes.map.e (/rbd/pnpm-volume/fd2eb835-c483-4238-9921-9a54026057fb/node_modules/.registry.npmjs.org/discord.js/12.4.1/node_modules/discord.js/src/structures/APIMessage.js:166:40)

    at Array.map (<anonymous>)

    at APIMessage.resolveData (/rbd/pnpm-volume/fd2eb835-c483-4238-9921-9a54026057fb/node_modules/.registry.npmjs.org/discord.js/12.4.1/node_modules/discord.js/src/structures/APIMessage.js:166:31)

    at TextChannel.send (/rbd/pnpm-volume/fd2eb835-c483-4238-9921-9a54026057fb/node_modules/.registry.npmjs.org/discord.js/12.4.1/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)

    at Promise (/rbd/pnpm-volume/fd2eb835-c483-4238-9921-9a54026057fb/node_modules/.registry.npmjs.org/discord-giveaways/4.2.1/node_modules/discord-giveaways/src/Manager.js:175:41)

    at new Promise (<anonymous>)

    at GiveawaysManager.start (/rbd/pnpm-volume/fd2eb835-c483-4238-9921-9a54026057fb/node_modules/.registry.npmjs.org/discord-giveaways/4.2.1/node_modules/discord-giveaways/src/Manager.js:128:16)

(node:3263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

(node:3263) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Androz2091** [comment]
Upgrade NodeJS to v12.
